trigger: none

pool:
  vmImage: ubuntu-latest

stages:

- stage: deploy
  jobs:
  - job: deploy
    steps:

      - task: AzureCLI@2
        displayName: 'Deploy Bicep file'
        inputs:
          azureSubscription: 'flash'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            # Deploying Bicep file
            az deployment sub create \
              --name $(Build.BuildNumber) \
              --location $(location) \
              --template-file $(Build.SourcesDirectory)/src/module.bicep \
              --parameters @$(Build.SourcesDirectory)/src/main.parameters.json
