trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:

      - task: CopyFiles@2
        displayName: 'Include templates in the artifact'
        inputs:
          SourceFolder: 'src'
          Contents: |
            main.bicep
            main.parameters.json
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish artifact'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'

- stage: deploy
  jobs:
  - job: deploy
    steps:

      - task: DownloadBuildArtifacts@0
        displayName: 'Download artifact'
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: AzureCLI@2
        displayName: 'deploy bicep template'
        inputs:
          azureSubscription: ToyWebsite
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group create  `
                --template-file $(System.ArtifactsDirectory)/module.bicep `
                --parameters $(System.ArtifactsDirectory)/main.parameters.json `
                --resource-group $(ResourceGroupName) `
                --parameters resourcePrefix=$(resourceprefix)