trigger: none

pool:
  vmImage: ubuntu-latest

stages:

- stage: deploy
  jobs:
  - job: deploy
    steps:

      - task: AzureCLI@2
        displayName: 'Deploy Bicep file'
        inputs:
          azureSubscription: 'ToyWebsite'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            # Creating a resource group
            az group create \
              --name $(ResourceGroupName) \
              --location $(location)
            # Deploying Bicep file
            az deployment group create \
              --name $(Build.BuildNumber) \
              --resource-group $(ResourceGroupName) \
              --template-file $(Build.SourcesDirectory)/src/module.bicep \
              --parameters @$(Build.SourcesDirectory)/src/main.parameters.json \
              --parameters location=$(location)
